[package]
name = "molecule"
version = "0.1.0"
authors = ["Christopher Kaag <christopher.kaag@gmail.com>"]

[dependencies]
diesel = { version = "1.3", features = ["sqlite"] }
dotenv = "0.10"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
diesel_migrations = "*"
diesel_codegen = "*"